name: counter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+36

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.9
  cupertino_icons: ^1.0.2
  fl_chart: ^0.60.0
  # path_provider: ^2.0.9
  firebase_core: ^1.17.0
  cloud_firestore: ^3.4.6
  provider: ^6.0.3
  firebase_auth: ^3.11.2
  shared_preferences: ^2.0.5
  flutter_datetime_picker: ^1.5.1
  confetti: ^0.7.0
  audioplayers: ^3.0.1
  #flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  # rxdart: ^0.27.7
  # toast: ^0.3.0
  # sound_mode: ^2.0.2
  # vibration: ^1.7.6
  percent_indicator: ^4.2.2
  http: ^0.13.5

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/sword.mp3

flutter_icons:
  android: true 
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/appstore.png"
  
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
