// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0FT56X29aN6V7_wl4mGWsHh17NiUalE',
    appId: '1:950899399586:web:8064d4d888b2c94432b0fb',
    messagingSenderId: '950899399586',
    projectId: 'herbooks-5894b',
    authDomain: 'herbooks-5894b.firebaseapp.com',
    storageBucket: 'herbooks-5894b.appspot.com',
    measurementId: 'G-4MK7KEEZJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXIMLioTQ-7D_RbnJVSBcdaJNWMi6ntQ',
    appId: '1:950899399586:android:7fbc7144f7ecb92432b0fb',
    messagingSenderId: '950899399586',
    projectId: 'herbooks-5894b',
    storageBucket: 'herbooks-5894b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbALEA7nBAL-Pxg-snSn7N0DzDb6HyC-A',
    appId: '1:950899399586:ios:05dc48c027b2e76632b0fb',
    messagingSenderId: '950899399586',
    projectId: 'herbooks-5894b',
    storageBucket: 'herbooks-5894b.appspot.com',
    iosClientId:
        '950899399586-3l82an4rk1hnqd5obrjbc29bu3veac03.apps.googleusercontent.com',
    iosBundleId: 'com.yoichiyy.herbooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbALEA7nBAL-Pxg-snSn7N0DzDb6HyC-A',
    appId: '1:950899399586:ios:78bc0c27ed65d40932b0fb',
    messagingSenderId: '950899399586',
    projectId: 'herbooks-5894b',
    storageBucket: 'herbooks-5894b.appspot.com',
    iosClientId:
        '950899399586-gpvl6qjtm26kna0ds5o0rvc2kvg5nc17.apps.googleusercontent.com',
    iosBundleId: 'com.yoichiyy.herbooks',
  );
}
