-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYpsRiQ7HCuxgYDbo
MToWpcsCs0d5UPXM38coywwXMligCgYIKoZIzj0DAQehRANCAAQHkjdT+xK2ynQQ
MHa4NuZtJB5IYy/ioL4cKtxWU2Epl3aZC1U/a3IMLJesGBVqClIJMQVo65WtWcsL
LoZCQPT3
-----END PRIVATE KEY-----